### ISSUE TITLE
Does not build with GHC 9.0.1

### ISSUE THREAD

**Issue by andreasabel** [coot/ghc-tags-plugin#50]
GHC changed their API, so this does not build under GHC 9.0.1:
```
Building library for ghc-tags-core-0.2.4.0..
[ 1 of 13] Compiling GhcTags.CTag.Header ( lib/GhcTags/CTag/Header.hs, dist/build/GhcTags/CTag/Header.o, dist/build/GhcTags/CTag/Header.dyn_o )
[ 2 of 13] Compiling GhcTags.Ghc      ( lib/GhcTags/Ghc.hs, dist/build/GhcTags/Ghc.o, dist/build/GhcTags/Ghc.dyn_o )

lib/GhcTags/Ghc.hs:30:1: error:
    Could not find module ‘BasicTypes’
    Use -v (or `:set -v` in ghci) to see a list of the files searched for.
   |
30 | import           BasicTypes   ( SourceText (..)
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^...
```

I went through an upgrade process like this in https://github.com/agda/hTags/commit/9ae9c3cc4475bf3ef245bfa0eaa397f03af327c8, you are welcome mine this for hints how to migrate.  

(What I didn't find out is how to migrate error reporting; https://github.com/agda/hTags/commit/9ae9c3cc4475bf3ef245bfa0eaa397f03af327c8#diff-894c9c531eb0d7c5f20f08d4008d2dfe4e48d3e542af618ed58a9b281cd28aa3R146-R150
if you happen to know how, please tell me.)

**Comment by coot** [comment]
I pushed changes to master which  allows to use it with `ghc-9.0.1`, I will very soon publish it on hackage.

**Comment by coot** [comment]
Done: https://hackage.haskell.org/package/ghc-tags-plugin-0.2.4.1, please reopen if you still have a problem with installing it for `ghc-9.0.1`.

Here you'll find how I dealt with error reporting  [diff](https://github.com/coot/ghc-tags-plugin/commit/41967bf1772ad5649861ce2c4b074b6cadc572f7#diff-8ccbd9aaf551b5fc8a28c83ab7fd4af86a068b4bfdec69c49c8e98693c1affdcR610-R622).

**Comment by andreasabel** [comment]
Thanks!
Looks like the build is now blocked on http://hackage.haskell.org/package/filepath-bytestring.  Unfortunately, I do not see an issue tracker for that package where I could report the problem.
```
$ cabal install ghc-tags-plugin
Resolving dependencies...
cabal: Could not resolve dependencies:
[__0] trying: ghc-tags-plugin-0.2.4.1 (user goal)
[__1] trying: filepath-bytestring-1.4.2.1.6 (dependency of ghc-tags-plugin)
[__2] next goal: base (dependency of ghc-tags-plugin)
[__2] rejecting: base-4.15.0.0/installed-4.15.0.0 (conflict:
filepath-bytestring => base>=4 && <4.15)
```
With `--allow-newer`, the build succeeds.

I sent an email to the maintainer of `filepath-bytestring`:
> Hello Joey,
> 
> I didn't find a bug tracker for filepath-bytestring, so I email you.
> 
> At http://hackage.haskell.org/package/filepath-bytestring/maintain you 
> can relax the upper bound for base to < 4.16 so that it builds with GHC 
> 9.0.1.
> 
> Thanks!
> Andreas

**Comment by coot** [comment]
Thanks for sending email to the maintainer.  I wonder why
```
allow-newer: filepath-bytestring:base
```
which I included in `cabal.project` was not taken into account? Did you installed from `hackage` with `cabal install` or from the repository?

**Comment by andreasabel** [comment]
I installed from hackage with `cabal install ghc-tags-plugin`.

**Comment by andreasabel** [comment]
This is done, the maintainer of filepath-bytestring released a new version for ghc 9.0.1!

**Comment by coot** [comment]
Thanks for letting me know, I'll release a new version too.

**Comment by coot** [comment]
Hmm, actually I think I don't need to release a new version; `cabal install -w ghc-9.0.1 ghc-tags-plugin` should now just work.

**Comment by andreasabel** [comment]
Yes, it does.

**Comment by andreasabel** [comment]
@coot: Same place, 19 months later...  To get `ghc-tags-core` build with GHC 9.4, I relaxed the `base` bound of `filepath-bytestring`: https://hackage.haskell.org/package/filepath-bytestring-1.4.2.1.11/revisions/  
I assumed you intend `ghc-tags-core` to work with GHC 9.4, otherwise, please let me know.

**Comment by coot** [comment]
That's what I included in `cabal.project` to support `ghc-9.4`, but they don't propagate.  I need to switch to a newer version of `filepath`.

**Comment by coot** [comment]
Hmm, `filepath` is bundled with `ghc`, I will need `filepath-bytestring` for some time.
